function move(x){
	if(x==0){
		$(".header").stop().animate({
			bottom:0
		})
	}else{
		$(".header").stop().animate({
			bottom:$(window).height()-$(".header").height()
		})
	}
	$('.hnindex').eq(x).addClass("hnindexsel").siblings().removeClass("hnindexsel");
	$(".page").eq(x).css("display","block").siblings().css("display","none");
	switch(x){
		case 1:
			$(".jsimg1").fadeIn();
			$(".jsimg2").animate({
				top:180,left:140
			});
			$(".jsimg3").animate({
				top:40,left:470
			});
			$(".jsimg4").animate({
				top:160,left:650
			});
			$(".jsimg5").animate({
				top:370,left:660
			});
			$(".jsimg6").animate({
				top:340,left:110
			});
			$(".jsimg7").animate({
				top:490,left:285
			});
			break;
		case 4:
			$(".jsp5jt").animate({
				width:689
			},function(){
				$(".jsp5_2").show().animate({
					top:136,left:170
				},function(){
					$(".jsp5_1").show().animate({
						top:230,left:156
					},function(){
						$(".jsp5_3").show().animate({
							top:160,left:516
						},function(){
							$(".jsp5_4").show().animate({
								top:288,left:700
							});
						});
					});
				});
			});
			break;
		case 7:
			$(".btint").stop().animate({marginTop:-210},3000);
			break;
		default:
			break;
	}
}
